import js from "@eslint/js";
import globals from "globals";

import stylistic from "@stylistic/eslint-plugin";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
    {
        plugins: {
            "@stylistic": stylistic,
        },

        languageOptions: {
            ecmaVersion: 2022,

            globals: {
                ...globals.browser,
                ...globals.jquery,
                ...globals.node,

                ActiveEffect: "readonly",
                Actor: "readonly",
                Actors: "readonly",
                ActorSheet: "readonly",
                AmplificationBackgroundVisionShader: "readonly",
                Application: "readonly",
                canvas: "readonly",
                ChatMessage: "readonly",
                Combat: "readonly",
                Combatant: "readonly",
                CombatTracker: "readonly",
                Compendium: "readonly",
                CompendiumCollection: "readonly",
                CompendiumDirectory: "readonly",
                CONFIG: "readonly",
                CONST: "readonly",
                DefaultTokenConfig: "readonly",
                Dialog: "readonly",
                Die: "readonly",
                dragRuler: "readonly",
                FilePicker: "readonly",
                fromUuid: "readonly",
                fromUuidSync: "readonly",
                Folder: "readonly",
                FormApplication: "readonly",
                FormDataExtended: "readonly",
                ForgeAPI: "readonly",
                foundry: "readonly",
                game: "readonly",
                getDocumentClass: "readonly",
                Handlebars: "readonly",
                HERO: "readonly",
                HeroRuler: "readonly",
                HeroSystem6eItem: "readonly",
                HexagonalGrid: "readonly",
                Hooks: "readonly",
                ImageHelper: "readonly",
                Item: "readonly",
                ItemDirectory: "readonly",
                Items: "readonly",
                ItemSheet: "readonly",
                loadTemplates: "readonly",
                NumericTerm: "readonly",
                Macro: "readonly",
                MeasuredTemplate: "readonly",
                OperatorTerm: "readonly",
                PIXI: "readonly",
                quench: "readonly",
                renderTemplate: "readonly",
                Roll: "readonly",
                RollTerm: "readonly",
                Ruler: "readonly",
                SceneNavigation: "readonly",
                SimpleCalendar: "readonly",
                TextEditor: "readonly",
                Token: "readonly",
                TokenDocument: "readonly",
                TokenHUD: "readonly",
                ui: "readonly",
                DetectionMode: "readonly",
                OutlineOverlayFilter: "readonly",
                DocumentSheetConfig: "readonly",
                ActiveEffectConfig: "readonly",
                Scene: "readonly",
                User: "readonly",
                VisionMode: "readonly",
            },
        },
    },
    js.configs.recommended,
    {
        // Extra rules beyond the recommended set
        rules: {
            "no-use-before-define": [
                "error",
                {
                    functions: false,
                    classes: true,
                    variables: true,
                    allowNamedExports: true,
                },
            ],
        },
    },
    eslintConfigPrettier,
];
